[tool.poetry]
name = "kursovaya-rabota"
version = "0.1.0"
description = ""
authors = ["Andrey <a.k.177@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
